// AUTO-GENERATED by scripts/generate-originals.mjs — do not edit by hand.
import type { Title } from "./types";

export const ORIGINALS: Title[] = [
  {
    "id": 9001,
    "name": "The Last Laugh",
    "overview": "A washed-up comedy legend reluctantly mentors the brash young rival who stole his big break — and discovers the punchline was on him all along.",
    "year": 2024,
    "rating": "TV-14",
    "matchPct": 90,
    "length": "1h 52m",
    "genres": [
      "Comedy",
      "Drama"
    ],
    "posterImage": "/originals/the-last-laugh.png",
    "backdropImage": "/originals/the-last-laugh-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9002,
    "name": "Cereal Killers",
    "overview": "Two feuding food-truck cooks turn the morning rush into all-out war, one questionable bowl of cereal at a time.",
    "year": 2023,
    "rating": "TV-PG",
    "matchPct": 91,
    "length": "2 Seasons",
    "genres": [
      "Comedy"
    ],
    "posterImage": "/originals/cereal-killers.png",
    "backdropImage": "/originals/cereal-killers-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9003,
    "name": "Out of Office",
    "overview": "When a struggling startup is forced to 'team-build' in a Wi-Fi-less mountain cabin, deadlines and dignity go offline together.",
    "year": 2024,
    "rating": "TV-14",
    "matchPct": 92,
    "length": "1 Season",
    "genres": [
      "Comedy"
    ],
    "posterImage": "/originals/out-of-office.png",
    "backdropImage": "/originals/out-of-office-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9004,
    "name": "Pug Life",
    "overview": "A burned-out bodyguard takes one last job: protecting the world's most pampered — and most dramatic — show pug.",
    "year": 2023,
    "rating": "PG",
    "matchPct": 90,
    "length": "1h 39m",
    "genres": [
      "Comedy"
    ],
    "posterImage": "/originals/pug-life.png",
    "backdropImage": "/originals/pug-life-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9005,
    "name": "Galaxy Brains",
    "overview": "Three hopelessly unqualified interns accidentally launch — and now must pilot — Earth's very first deep-space starship.",
    "year": 2024,
    "rating": "TV-14",
    "matchPct": 90,
    "length": "1 Season",
    "genres": [
      "Sci-Fi",
      "Comedy"
    ],
    "posterImage": "/originals/galaxy-brains.png",
    "backdropImage": "/originals/galaxy-brains-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9006,
    "name": "Glass Harbor",
    "overview": "A grieving lighthouse keeper uncovers a decades-old secret buried beneath the waves of a fog-bound coastal town.",
    "year": 2024,
    "rating": "TV-MA",
    "matchPct": 97,
    "length": "2 Seasons",
    "genres": [
      "Drama",
      "Mystery"
    ],
    "posterImage": "/originals/glass-harbor.png",
    "backdropImage": "/originals/glass-harbor-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9007,
    "name": "The Undertow",
    "overview": "A detective returns to her coastal hometown to solve a disappearance that mirrors the one that shattered her own childhood.",
    "year": 2023,
    "rating": "R",
    "matchPct": 96,
    "length": "2h 11m",
    "genres": [
      "Thriller",
      "Drama"
    ],
    "posterImage": "/originals/the-undertow.png",
    "backdropImage": "/originals/the-undertow-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9008,
    "name": "Ashes of Atlas",
    "overview": "In a continent choked by endless ash, a hardened smuggler must carry the last living seed across a ruined frontier.",
    "year": 2024,
    "rating": "PG-13",
    "matchPct": 90,
    "length": "2h 24m",
    "genres": [
      "Sci-Fi",
      "Drama"
    ],
    "posterImage": "/originals/ashes-of-atlas.png",
    "backdropImage": "/originals/ashes-of-atlas-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9009,
    "name": "Concrete Roses",
    "overview": "A teenage poet fights to make her voice heard above the noise of a crumbling neighborhood that everyone else has given up on.",
    "year": 2023,
    "rating": "TV-MA",
    "matchPct": 92,
    "length": "1 Season",
    "genres": [
      "Drama"
    ],
    "posterImage": "/originals/concrete-roses.png",
    "backdropImage": "/originals/concrete-roses-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9010,
    "name": "The Reckoning",
    "overview": "A small-town lawyer risks everything to take on the corporation that quietly poisoned her family — and her town.",
    "year": 2024,
    "rating": "R",
    "matchPct": 90,
    "length": "2h 6m",
    "genres": [
      "Crime",
      "Drama"
    ],
    "posterImage": "/originals/the-reckoning.png",
    "backdropImage": "/originals/the-reckoning-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  }
];
