// AUTO-GENERATED by scripts/generate-starring.mjs — do not edit by hand.
import type { Title } from "./types";

export const STARRING: Title[] = [
  {
    "id": 9101,
    "name": "Redbeard",
    "overview": "A legendary outlaw thought long dead resurfaces to settle one final score on the lawless frontier of the high seas.",
    "year": 2024,
    "rating": "PG-13",
    "matchPct": 92,
    "length": "2h 7m",
    "genres": [
      "Action",
      "Adventure"
    ],
    "posterImage": "/starring/redbeard.png",
    "backdropImage": "/starring/redbeard-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9102,
    "name": "Genesis Protocol",
    "overview": "When an AI awakens wearing the face of its creator, one engineer must decide what makes us human before it's too late.",
    "year": 2024,
    "rating": "TV-MA",
    "matchPct": 98,
    "length": "1 Season",
    "genres": [
      "Sci-Fi",
      "Thriller"
    ],
    "posterImage": "/starring/genesis-protocol.png",
    "backdropImage": "/starring/genesis-protocol-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9103,
    "name": "The Long Game",
    "overview": "A career con artist is pulled into one last scheme — where the only way out is to outplay everyone who ever trusted him.",
    "year": 2023,
    "rating": "R",
    "matchPct": 94,
    "length": "2h 14m",
    "genres": [
      "Crime",
      "Drama"
    ],
    "posterImage": "/starring/the-long-game.png",
    "backdropImage": "/starring/the-long-game-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9104,
    "name": "Static",
    "overview": "Strange signals bleed through every screen in a remote town, and the man who hears them first may be the only one who can stop them.",
    "year": 2024,
    "rating": "R",
    "matchPct": 92,
    "length": "1h 48m",
    "genres": [
      "Horror"
    ],
    "posterImage": "/starring/static.png",
    "backdropImage": "/starring/static-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9105,
    "name": "Beard Necessities",
    "overview": "A wildly overconfident slacker bluffs his way into running a high-end barbershop with absolutely no idea what he's doing.",
    "year": 2023,
    "rating": "TV-14",
    "matchPct": 98,
    "length": "2 Seasons",
    "genres": [
      "Comedy"
    ],
    "posterImage": "/starring/beard-necessities.png",
    "backdropImage": "/starring/beard-necessities-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9106,
    "name": "Ironwood",
    "overview": "A reclusive craftsman returns to the town that broke him, forcing a reckoning years in the making.",
    "year": 2024,
    "rating": "TV-MA",
    "matchPct": 94,
    "length": "1 Season",
    "genres": [
      "Drama"
    ],
    "posterImage": "/starring/ironwood.png",
    "backdropImage": "/starring/ironwood-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9107,
    "name": "Dust & Ash",
    "overview": "A drifter with nothing left to lose rides into a dying town and becomes its last, unlikely hope.",
    "year": 2023,
    "rating": "R",
    "matchPct": 92,
    "length": "2h 19m",
    "genres": [
      "Western",
      "Drama"
    ],
    "posterImage": "/starring/dust-and-ash.png",
    "backdropImage": "/starring/dust-and-ash-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9108,
    "name": "Closer",
    "overview": "Two strangers keep crossing paths across one unforgettable city, daring to believe the timing might finally be right.",
    "year": 2024,
    "rating": "PG-13",
    "matchPct": 92,
    "length": "1h 56m",
    "genres": [
      "Romance",
      "Drama"
    ],
    "posterImage": "/starring/closer.png",
    "backdropImage": "/starring/closer-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9109,
    "name": "The Ember Crown",
    "overview": "A blacksmith's son discovers he's the last heir to a fallen kingdom — and the only one who can reclaim its burning throne.",
    "year": 2024,
    "rating": "TV-14",
    "matchPct": 92,
    "length": "1 Season",
    "genres": [
      "Fantasy",
      "Adventure"
    ],
    "posterImage": "/starring/the-ember-crown.png",
    "backdropImage": "/starring/the-ember-crown-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    "id": 9110,
    "name": "The Last Commit",
    "overview": "A burned-out developer uncovers a deadly secret buried in his company's code, and shipping the truth could cost him everything.",
    "year": 2024,
    "rating": "TV-MA",
    "matchPct": 94,
    "length": "1h 51m",
    "genres": [
      "Thriller"
    ],
    "posterImage": "/starring/the-last-commit.png",
    "backdropImage": "/starring/the-last-commit-wide.png",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  }
];
